const BANCO_FACIL = [

    /* ===================== CONJUNCIONES (20) ===================== */
    {q:"¿Qué es una conjunción?",a:["Palabra invariable que une palabras u oraciones","Palabra que nombra","Palabra que indica acción","Palabra que califica"],c:0},
    {q:"Las conjunciones son palabras:",a:["Invariables","Variables","Conjugadas","Derivadas"],c:0},
    {q:"Las conjunciones coordinantes unen:",a:["Elementos del mismo valor","Elementos subordinados","Solo verbos","Solo adjetivos"],c:0},
    {q:"Las conjunciones subordinantes introducen:",a:["Oraciones dependientes","Sustantivos","Adjetivos","Pronombres"],c:0},
    {q:"¿Cuál es una conjunción copulativa?",a:["y","pero","o","aunque"],c:0},
    {q:"Las copulativas expresan:",a:["Suma o unión","Oposición","Alternativa","Condición"],c:0},
    {q:"¿Cuál es una conjunción disyuntiva?",a:["o","y","ni","pero"],c:0},
    {q:"Las disyuntivas indican:",a:["Elección","Suma","Oposición","Causa"],c:0},
    {q:"¿Cuál es una conjunción adversativa?",a:["pero","y","o","ni"],c:0},
    {q:"Las adversativas expresan:",a:["Oposición","Suma","Elección","Explicación"],c:0},
    {q:"¿Cuál es una conjunción explicativa?",a:["es decir","pero","o","ni"],c:0},
    {q:"Las explicativas aclaran lo:",a:["Anterior","Posterior","Sustantivo","Verbo"],c:0},
    {q:"¿Cuál es una conjunción causal?",a:["porque","y","o","pero"],c:0},
    {q:"Las causales indican:",a:["Motivo","Tiempo","Condición","Lugar"],c:0},
    {q:"¿Cuál es una conjunción consecutiva?",a:["por lo tanto","y","o","pero"],c:0},
    {q:"Las consecutivas indican:",a:["Resultado","Causa","Tiempo","Oposición"],c:0},
    {q:"¿Cuál es una conjunción condicional?",a:["si","y","pero","o"],c:0},
    {q:"Las condicionales indican:",a:["Condición","Resultado","Causa","Tiempo"],c:0},
    {q:"¿Cuál es una conjunción concesiva?",a:["aunque","y","o","pero"],c:0},
    {q:"Las concesivas expresan:",a:["Dificultad","Suma","Elección","Causa"],c:0},
    
    /* ===================== ADVERBIOS (20) ===================== */
    {q:"El adverbio modifica:",a:["Verbo, adjetivo y adverbio","Sustantivo","Pronombre","Artículo"],c:0},
    {q:"Los adverbios son palabras:",a:["Invariables","Variables","Conjugadas","Derivadas"],c:0},
    {q:"¿Cuál es adverbio de lugar?",a:["aquí","ayer","muy","no"],c:0},
    {q:"Los adverbios de lugar indican:",a:["Dónde","Cuándo","Cuánto","Cómo"],c:0},
    {q:"¿Cuál es adverbio de tiempo?",a:["ayer","aquí","muy","bien"],c:0},
    {q:"Los adverbios de tiempo indican:",a:["Cuándo","Dónde","Cómo","Cuánto"],c:0},
    {q:"¿Cuál es adverbio de cantidad?",a:["muy","ayer","aquí","no"],c:0},
    {q:"Los adverbios de cantidad indican:",a:["Intensidad","Lugar","Tiempo","Modo"],c:0},
    {q:"¿Cuál es adverbio de modo?",a:["bien","ayer","aquí","no"],c:0},
    {q:"Los adverbios de modo indican:",a:["Cómo","Dónde","Cuándo","Cuánto"],c:0},
    {q:"¿Cuál es adverbio de afirmación?",a:["sí","no","ayer","aquí"],c:0},
    {q:"¿Cuál es adverbio de negación?",a:["no","sí","bien","ayer"],c:0},
    {q:"¿Cuál es adverbio de duda?",a:["quizás","sí","no","aquí"],c:0},
    {q:"Los adverbios de duda expresan:",a:["Incertidumbre","Lugar","Cantidad","Modo"],c:0},
    {q:"Los adverbios pueden modificar:",a:["Verbos","Adjetivos","Otros adverbios","Todas"],c:3},
    {q:"'Muy alto' contiene un adverbio de:",a:["Cantidad","Tiempo","Lugar","Modo"],c:0},
    {q:"'Aquí estoy' contiene un adverbio de:",a:["Lugar","Tiempo","Modo","Cantidad"],c:0},
    {q:"'Ayer fui' contiene un adverbio de:",a:["Tiempo","Lugar","Modo","Cantidad"],c:0},
    {q:"'Bien hecho' contiene un adverbio de:",a:["Modo","Tiempo","Lugar","Cantidad"],c:0},
    {q:"Los adverbios no concuerdan en:",a:["Género ni número","Tiempo","Persona","Modo"],c:0},
    
    /* ===================== VERBOS (20) ===================== */
    {q:"El verbo expresa:",a:["Acción o estado","Objeto","Cantidad","Relación"],c:0},
    {q:"El verbo concuerda con:",a:["El sujeto","El adjetivo","El adverbio","La conjunción"],c:0},
    {q:"El modo indicativo expresa:",a:["Hechos reales","Órdenes","Dudas","Deseos"],c:0},
    {q:"El modo subjuntivo expresa:",a:["Deseo o duda","Hechos reales","Orden","Tiempo"],c:0},
    {q:"El modo imperativo expresa:",a:["Orden","Duda","Tiempo","Número"],c:0},
    {q:"La voz activa indica que el sujeto:",a:["Realiza la acción","Recibe la acción","Niega","Ordena"],c:0},
    {q:"La voz pasiva indica que el sujeto:",a:["Recibe la acción","Realiza la acción","Ordena","Niega"],c:0},
    {q:"Un verbo transitivo necesita:",a:["Objeto directo","Adjetivo","Adverbio","Preposición"],c:0},
    {q:"Un verbo intransitivo:",a:["Tiene sentido completo","Necesita objeto","Siempre es pasivo","No existe"],c:0},
    {q:"El tiempo verbal indica:",a:["Cuándo ocurre la acción","Quién actúa","Cómo ocurre","Por qué"],c:0},
    {q:"El presente indica:",a:["Acción actual","Acción pasada","Acción futura","Condición"],c:0},
    {q:"El pasado indica:",a:["Acción ya realizada","Acción futura","Deseo","Orden"],c:0},
    {q:"El futuro indica:",a:["Acción que ocurrirá","Acción pasada","Deseo","Orden"],c:0},
    {q:"El infinitivo termina en:",a:["ar, er, ir","ado, ido","ando","iendo"],c:0},
    {q:"El participio termina en:",a:["ado, ido","ar, er, ir","ando","iendo"],c:0},
    {q:"El gerundio termina en:",a:["ando, iendo","ado, ido","ar, er, ir","ido"],c:0},
    {q:"Los verbos pueden ser:",a:["Regulares e irregulares","Solo regulares","Solo irregulares","Solo pasivos"],c:0},
    {q:"Un verbo irregular:",a:["Cambia su raíz","No se conjuga","Es pasivo","Es copulativo"],c:0},
    {q:"Los verbos copulativos son:",a:["ser, estar, parecer","tener, hacer, decir","ir, venir, salir","amar, correr, vivir"],c:0},
    {q:"Los verbos copulativos unen el sujeto con:",a:["Un atributo","Un objeto","Un adverbio","Una conjunción"],c:0},
    
    /* ===================== MORFOLOGÍA (20) ===================== */
    {q:"La morfología estudia:",a:["La estructura de las palabras","Los sonidos","El significado","Las oraciones"],c:0},
    {q:"Un morfema es:",a:["Unidad mínima de significado","Letra","Sílaba","Sonido"],c:0},
    {q:"La raíz es:",a:["Parte principal de la palabra","El sufijo","El prefijo","El artículo"],c:0},
    {q:"Un prefijo se coloca:",a:["Antes de la raíz","Después de la raíz","Dentro de la raíz","Después del sufijo"],c:0},
    {q:"Un sufijo se coloca:",a:["Después de la raíz","Antes de la raíz","Dentro de la raíz","Antes del prefijo"],c:0},
    {q:"El morfema lexical es:",a:["La raíz","El género","El número","El tiempo"],c:0},
    {q:"El morfema gramatical expresa:",a:["Tiempo, número, persona","La raíz","El sonido","El significado"],c:0},
    {q:"El género puede ser:",a:["Masculino y femenino","Plural y singular","Pasado y presente","Activo y pasivo"],c:0},
    {q:"El número puede ser:",a:["Singular y plural","Masculino y femenino","Activo y pasivo","Simple y compuesto"],c:0},
    {q:"La flexión modifica:",a:["Forma de la palabra","La raíz","El sonido","El significado base"],c:0},
    {q:"La derivación forma:",a:["Palabras nuevas","Oraciones","Sonidos","Tiempos"],c:0},
    {q:"La composición une:",a:["Dos palabras","Dos sonidos","Dos sílabas","Dos tiempos"],c:0},
    {q:"El lexema contiene:",a:["Significado principal","Género","Número","Tiempo"],c:0},
    {q:"El morfema puede ser:",a:["Lexical o gramatical","Verbal o nominal","Activo o pasivo","Simple o compuesto"],c:0},
    {q:"Un morfema libre puede:",a:["Ser palabra","No existir","Ser sufijo","Ser prefijo"],c:0},
    {q:"Un morfema ligado:",a:["No puede ir solo","Es una palabra","Es un verbo","Es un adverbio"],c:0},
    {q:"Los morfemas flexivos expresan:",a:["Género y número","Raíz","Significado","Sonido"],c:0},
    {q:"Los morfemas derivativos forman:",a:["Nuevas palabras","Sonidos","Sílabas","Tiempos"],c:0},
    {q:"La morfología pertenece a la:",a:["Gramática","Fonética","Semántica","Pragmática"],c:0},
    {q:"Las palabras se analizan morfológicamente en:",a:["Raíz y morfemas","Sonidos","Sílabas","Oraciones"],c:0},
    
    /* ===================== FUNCIONES DEL LENGUAJE (20) ===================== */
    {q:"La función referencial se centra en:",a:["Informar","Ordenar","Emocionar","Estética"],c:0},
    {q:"La función apelativa busca:",a:["Influir en el receptor","Informar","Expresar emociones","La forma"],c:0},
    {q:"La función emotiva expresa:",a:["Sentimientos del emisor","Información","Orden","Forma"],c:0},
    {q:"La función poética se centra en:",a:["La forma del mensaje","El emisor","El receptor","El canal"],c:0},
    {q:"La función fática verifica:",a:["El canal","La información","El emisor","El código"],c:0},
    {q:"La función metalingüística habla sobre:",a:["El lenguaje","El receptor","El emisor","La realidad"],c:0},
    {q:"'Hola, ¿me escuchas?' es función:",a:["Fática","Poética","Referencial","Emotiva"],c:0},
    {q:"'Estoy triste' es función:",a:["Emotiva","Apelativa","Referencial","Poética"],c:0},
    {q:"'Cierra la puerta' es función:",a:["Apelativa","Referencial","Emotiva","Poética"],c:0},
    {q:"'El agua hierve a 100°' es función:",a:["Referencial","Poética","Emotiva","Fática"],c:0},
    {q:"'Qué hermosa noche' es función:",a:["Poética","Referencial","Apelativa","Fática"],c:0},
    {q:"'La palabra verbo es...' es función:",a:["Metalingüística","Fática","Poética","Emotiva"],c:0},
    {q:"La función poética busca:",a:["Belleza","Información","Orden","Contacto"],c:0},
    {q:"La función referencial se enfoca en:",a:["El contexto","El emisor","El receptor","El canal"],c:0},
    {q:"La función apelativa se enfoca en:",a:["El receptor","El emisor","El mensaje","El código"],c:0},
    {q:"La función emotiva se enfoca en:",a:["El emisor","El receptor","El canal","El código"],c:0},
    {q:"La función fática se enfoca en:",a:["El canal","El mensaje","El emisor","El contexto"],c:0},
    {q:"La función metalingüística se enfoca en:",a:["El código","El canal","El emisor","El receptor"],c:0},
    {q:"Las funciones del lenguaje fueron propuestas por:",a:["Jakobson","Saussure","Chomsky","Platón"],c:0},
    {q:"Las funciones del lenguaje explican:",a:["Cómo usamos el lenguaje","Cómo se conjuga","Cómo se escribe","Cómo se pronuncia"],c:0}
    ];